Unpin `graphene` version
Summary:
[Our GitHub CI is failing](https://github.com/facebook/sapp/runs/3950857872?check_suite_focus=true) because graphene==2.1.3 uses [aliases to Abstract Base Classes in the collections module, which were removed in python versions greater than 3.10](https://docs.python.org/3.9/whatsnew/3.9.html#you-should-check-for-deprecationwarning-in-your-code)

```
ImportError: Failed to import test module: filter_test
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.0/x64/lib/python3.10/unittest/loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
  File "/home/runner/work/sapp/sapp/sapp/tests/filter_test.py", line 9, in <module>
    from ..filter import FilterValidationException, StoredFilter
  File "/home/runner/work/sapp/sapp/sapp/filter.py", line 17, in <module>
    from .models import Base
  File "/home/runner/work/sapp/sapp/sapp/models.py", line 17, in <module>
    from graphene_sqlalchemy.converter import (
  File "/opt/hostedtoolcache/Python/3.10.0/x64/lib/python3.10/site-packages/graphene_sqlalchemy/__init__.py", line 1, in <module>
    from .types import SQLAlchemyObjectType
  File "/opt/hostedtoolcache/Python/3.10.0/x64/lib/python3.10/site-packages/graphene_sqlalchemy/types.py", line 9, in <module>
    from graphene import Field
  File "/opt/hostedtoolcache/Python/3.10.0/x64/lib/python3.10/site-packages/graphene/__init__.py", line 3, in <module>
    from .types import (
  File "/opt/hostedtoolcache/Python/3.10.0/x64/lib/python3.10/site-packages/graphene/types/__init__.py", line 4, in <module>
    from .objecttype import ObjectType
  File "/opt/hostedtoolcache/Python/3.10.0/x64/lib/python3.10/site-packages/graphene/types/objecttype.py", line 4, in <module>
    from .field import Field
  File "/opt/hostedtoolcache/Python/3.10.0/x64/lib/python3.10/site-packages/graphene/types/field.py", line 2, in <module>
    from collections import Mapping, OrderedDict
ImportError: cannot import name 'Mapping' from 'collections' (/opt/hostedtoolcache/Python/3.10.0/x64/lib/python3.10/collections/__init__.py)
```

Our options to solve this are:
1. Unpin the graphene version in requirements.txt
2. Force GitHub actions to run with python versions < 3.10
3. Update the graphene library upstream to switch imports by sys version to support 3.10

(3) will take too long and require too much effort if (1) works for us. (2) would result in SAPP eventually being stuck on an old version of python. (1) seems to be the best way to go, however we might not have enough tests to ensure nothing breaks with this upgrade

Reviewed By: onionymous

Differential Revision: D31834093

fbshipit-source-id: c18100f2e13d4369e3a8b5e25a0cecdf81b487b4