Fix typing for TypedDict for Python versions earlier than Python 3.8
Summary:
A user setting up SAPP for development will be unable to run SAPP with a Python version earlier than Python 3.8

`typing.TypedDict` was added in [Python 3.8](https://docs.python.org/3/whatsnew/3.8.html#typing). The fix is to check for the Python version and switch to importing `typing_extensions.TypedDict` for Python versions earlier than 3.8.

### Steps to Reproduce
1. Follow the development setup [here](https://github.com/facebook/sapp#development-environment-setup)
2. Running `python3 -m sapp.cli server` will result in the following traceback:
```
  File "/opt/homebrew/Cellar/python37/3.7.5_3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/homebrew/Cellar/python37/3.7.5_3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/edq/open_source/sapp/sapp/cli.py", line 12, in <module>
    from .cli_lib import commands, common_options
  File "/Users/edq/open_source/sapp/sapp/cli_lib.py", line 17, in <module>
    from .context import Context, pass_context
  File "/Users/edq/open_source/sapp/sapp/context.py", line 13, in <module>
    from .pipeline.base_parser import BaseParser
  File "/Users/edq/open_source/sapp/sapp/pipeline/__init__.py", line 11, in <module>
    from typing import (
ImportError: cannot import name 'TypedDict' from 'typing' (/opt/homebrew/Cellar/python37/3.7.5_3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/typing.py)
```

Reviewed By: gbleaney

Differential Revision: D27712119

fbshipit-source-id: dbc578b5b8c22d014fabe494c2d97b1c7fe301c5