added `default=str` arguement to json.dumps call in filter_run (#64)
Summary:
This PR adds  `default=str` arguement to json.dumps call in the `filter_run` function of   [filters.py](https://github.com/facebook/sapp/blob/main/sapp/ui/filters.py)

Without this arguement the function throws  a type error when called

```python
TypeError: "Object of type datetime is not JSON serializable"
```

This is because the object passed into json.dumps contains a datetime element which cannot be serialized unless converted to a string

Pull Request resolved: https://github.com/facebook/sapp/pull/64

Reviewed By: 0xedward

Differential Revision: D32571837

Pulled By: grievejia

fbshipit-source-id: 93d9860319f0729bb3cb2ce15b199c7c2485da05