Fix typing for `Literal` to support Python 3.7+
Summary:
Since SAPP currently supports Python 3.7, we will need to import `Literal` from `typing_extensions` for Python version earlier than 3.8

## Steps to Reproduce
1. Follow the development setup [here](https://github.com/facebook/sapp#development-environment-setup)
2. Running `python3 -m sapp.cli server` will result in the following traceback:
```
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python37/3.7.5_3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/homebrew/Cellar/python37/3.7.5_3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/edq/open_source/sapp/sapp/cli.py", line 18, in <module>
    from .pipeline.mariana_trench_parser import Parser as MarianaTrenchParser
  File "/Users/edq/open_source/sapp/sapp/pipeline/mariana_trench_parser.py", line 10, in <module>
    from typing import (
ImportError: cannot import name 'Literal' from 'typing' (/opt/homebrew/Cellar/python37/3.7.5_3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/typing.py)
```

Reviewed By: gbleaney

Differential Revision: D27984058

fbshipit-source-id: ea60e3c6375ac7976c5fc662ed663b2e60ba09b5