Add None check for sys in CLFAux __del__
Summary:
Users for cfgr-cv are getting the error `AttributeError: 'NoneType' object has no attribute 'is_finalizing'` based on https://fburl.com/workplace/uqwvoast

Adding ligen API that returns the result of `_Py_isFinalizing` so we can check this instead of sys is not None etc.

ig-fbcode-test

Reviewed By: pranavtbhat

Differential Revision: D46175147

fbshipit-source-id: b6bec272368b56188c03b806f0bb81a1a30a7259