Fix error in open source sapp
Summary:
It looks like D66775541 broke open source sapp:
```
File "/home/lzy/.local/lib/python3.12/site-packages/sapp/pipeline/trim_trace_graph.py", line 26, in run
if not summary["affected_file_sets"]:
~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'affected_file_sets'
```

Let's fix it.

Reviewed By: alambert

Differential Revision: D73654054

fbshipit-source-id: d3fc98374d5c63d35181055f3c090dd49c799dff