Fix type error in backfill logic for `primary_keys` table
Summary:
If we have no record of the highest used primary key, we query for the highest used id use that value to backfill the `primary_keys` table.

This diff fixes a bug where this code was passing a `DBID` into SQLAlchemy rather than an `int`, causing exceptions like this:

```
sqlalchemy.exc.InterfaceError: (sqlite3.InterfaceError) Error binding parameter 1 - probably unsupported type.
[SQL: INSERT INTO primary_keys(table_name, current_id)                     VALUES (?, ?)]
[parameters: ('Issue', <IssueDBID(id=1) object at 0x7f5baf0e97c0>)]
```

Reviewed By: yaabdalla

Differential Revision: D46079269

fbshipit-source-id: 8a55d13884be47409c271f18e659b7a44ebed609