Fix `npm run-script build`
Summary:
D28605644 (https://github.com/facebook/sapp/commit/6d61145d8ea2185b56c7a10d0c580a72ed71a12e) broke `npm run-script build`, because `postcss` versions were bumped to a version with breaking changes. This was found by going through each commit from newest to oldest in the SAPP GitHub repo and running `npm install && npm run-script build` until the command was successful.

**This issue is preventing us from publishing new versions of SAPP to PyPi and preventing our MLH fellows from working on SAPP UI issues.**

## Steps to reproduce:
1. `git clone https://github.com/facebook/sapp.git && cd sapp` to checkout the latest commit on `master` branch
3. `cd sapp/ui/frontend && npm install`
4. `npm run-script build --verbose`
```
...

./src/index.css
TypeError: this.getOptions is not a function

...
```

Reviewed By: dkgi

Differential Revision: D28811486

fbshipit-source-id: 2d1d59bab74c8635d36eb17e0579793b43e48b47